/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_walterreyes;

import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Lab6_WalterReyes extends javax.swing.JFrame {

    /**
     * Creates new form Lab6_WalterReyes
     */
    public Lab6_WalterReyes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClaudiList = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre_Lista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nombre_Programa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_anime = new javax.swing.JRadioButton();
        b_serie = new javax.swing.JRadioButton();
        b_documental = new javax.swing.JRadioButton();
        b_película = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        JS_Puntuación = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        Año = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        b_comedia = new javax.swing.JRadioButton();
        b_romance = new javax.swing.JRadioButton();
        b_terror = new javax.swing.JRadioButton();
        b_syfy = new javax.swing.JRadioButton();
        b_suspenso = new javax.swing.JRadioButton();
        b_acción = new javax.swing.JRadioButton();
        Guardar_Lista = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        Crear_ClaudiList = new javax.swing.JButton();
        Agregar_Programa = new javax.swing.JButton();
        Cargar_Archivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_Lista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de la Lista:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del programa:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Programa: ");

        buttonGroup1.add(b_anime);
        b_anime.setText("Anime");

        buttonGroup1.add(b_serie);
        b_serie.setText("Serie");

        buttonGroup1.add(b_documental);
        b_documental.setText("Documental");

        buttonGroup1.add(b_película);
        b_película.setText("Película");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Puntuación: ");

        JS_Puntuación.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Año de lanzamiento");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Genero");

        b_comedia.setText("Comedia ");

        b_romance.setText("Romance");

        b_terror.setText("terror");

        b_syfy.setText("Syfy");

        b_suspenso.setText("Suspenso");

        b_acción.setText("Acción");

        Guardar_Lista.setText("Guardar");
        Guardar_Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_ListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(JS_Puntuación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_anime)
                                .addGap(18, 18, 18)
                                .addComponent(b_serie)
                                .addGap(18, 18, 18)
                                .addComponent(b_documental)
                                .addGap(18, 18, 18)
                                .addComponent(b_película))
                            .addComponent(Nombre_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(b_comedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_romance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_terror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_syfy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_suspenso)
                        .addGap(18, 18, 18)
                        .addComponent(b_acción)))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(Nombre_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(Guardar_Lista)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(b_anime)
                    .addComponent(b_serie)
                    .addComponent(b_documental)
                    .addComponent(b_película))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JS_Puntuación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(b_comedia)
                    .addComponent(b_romance)
                    .addComponent(b_terror)
                    .addComponent(b_syfy)
                    .addComponent(b_suspenso)
                    .addComponent(b_acción))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(Guardar_Lista))
        );

        javax.swing.GroupLayout ClaudiListLayout = new javax.swing.GroupLayout(ClaudiList.getContentPane());
        ClaudiList.getContentPane().setLayout(ClaudiListLayout);
        ClaudiListLayout.setHorizontalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClaudiListLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        ClaudiListLayout.setVerticalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClaudiListLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Crear_ClaudiList.setText("Crear Claudilist");
        Crear_ClaudiList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_ClaudiListActionPerformed(evt);
            }
        });

        Agregar_Programa.setText("Agregar Programa");
        Agregar_Programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ProgramaActionPerformed(evt);
            }
        });

        Cargar_Archivo.setText("Cargar Archivo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Fecha", "Tipo", "Género"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        cb_Lista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ListaItemStateChanged(evt);
            }
        });

        jButton1.setText("Guardar  Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Crear_ClaudiList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agregar_Programa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cargar_Archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cb_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Crear_ClaudiList, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Agregar_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Cargar_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_ClaudiListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_ClaudiListActionPerformed
        ClaudiList.setModal(true);
        ClaudiList.pack();
       ClaudiList.setLocationRelativeTo(this);
        ClaudiList.setVisible(true);   
    }//GEN-LAST:event_Crear_ClaudiListActionPerformed

    private void Agregar_ProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar_ProgramaActionPerformed

    private void Guardar_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_ListaActionPerformed
        String nombre = "";
        int puntuación = 0;
        String fecha = "";
        String tipo = "";
        String genero = "";
        String Nombre_lista = "";
        Boolean f = true;
        
        
        try{
         nombre = Nombre_Programa.getText();
         if((int)JS_Puntuación.getValue()> 10){    
         puntuación = (int)JS_Puntuación.getValue();
         }
         fecha = Año.getText();
         if(b_anime.isSelected()){
             tipo = "Anime";
         }
         if(b_serie.isSelected()){
             tipo = "Serie";
         }
         if(b_documental.isSelected()){
             tipo = "Documental";
         }
         if(b_película.isSelected()){
             tipo = "Película";
         }
         if(b_comedia.isSelected()){
             genero = "Comedia";
         }
         if(b_romance.isSelected()){
             genero = "Romance";
         }
         if(b_terror.isSelected()){
             genero = "Terror";
         }
         if(b_syfy.isSelected()){
             genero = "SyFy";
         }
         if(b_suspenso.isSelected()){
             genero = "Suspenso";
         }
         if(b_acción.isSelected()){
             genero = "Acción";
         }
         Nombre_lista = Nombre_Lista.getText();
         
        }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Ocurrió un error al crear la Lista");
         f = false;
        }
        if(f== true){
            JOptionPane.showMessageDialog(null,"Se ha guardado la lista exitosamente");
                  DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();
                  Programas p = new Programas(nombre,puntuación,fecha,tipo,genero);
                cb_Lista.setModel(modelo);
                claudilist cl = new claudilist();
                cl.setNombre(Nombre_lista);
                cl.getLista().add(p);
                  modelo.addElement(cl);
                  Nombre_Programa.setText("");
                  Nombre_Lista.setText("");
                  Año.setText("");
                  
                  ClaudiList.setVisible(false);
        }
        
    }//GEN-LAST:event_Guardar_ListaActionPerformed

    private void cb_ListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ListaItemStateChanged
    DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        eliminar();
        if (evt.getStateChange() == 1) {
            
            claudilist c = (claudilist) modelo.getSelectedItem();
           
            for (Programas p : c.getLista()) {

                Object[] newRow = {
                    p.getNombre(),
                    p.getPuntuación(),
                    p.getFecha(),
                    p.getTipo(),
                    p.getGenero()
                };

                modelo2.addRow(newRow);
            }

            
        }
    }//GEN-LAST:event_cb_ListaItemStateChanged
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cb_Lista.getSelectedIndex() >= 0) {

            try {
                ((claudilist) (cb_Lista.getSelectedItem())).escribirArchivo();
            } catch (IOException ex) {

            }

            JOptionPane.showMessageDialog(this, "El archivo se ha guardo correctamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6_WalterReyes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Programa;
    private javax.swing.JTextField Año;
    private javax.swing.JButton Cargar_Archivo;
    private javax.swing.JDialog ClaudiList;
    private javax.swing.JButton Crear_ClaudiList;
    private javax.swing.JButton Guardar_Lista;
    private javax.swing.JSpinner JS_Puntuación;
    private javax.swing.JTextField Nombre_Lista;
    private javax.swing.JTextField Nombre_Programa;
    private javax.swing.JRadioButton b_acción;
    private javax.swing.JRadioButton b_anime;
    private javax.swing.JRadioButton b_comedia;
    private javax.swing.JRadioButton b_documental;
    private javax.swing.JRadioButton b_película;
    private javax.swing.JRadioButton b_romance;
    private javax.swing.JRadioButton b_serie;
    private javax.swing.JRadioButton b_suspenso;
    private javax.swing.JRadioButton b_syfy;
    private javax.swing.JRadioButton b_terror;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_Lista;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
