/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_walterreyes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;

/**
 *
 * @author hp
 */
public class Lab8_WalterReyes extends javax.swing.JFrame {

    /**
     * Creates new form Lab6_WalterReyes
     */
    public Lab8_WalterReyes() {
        initComponents();
        // activo la canción
        Audio a = new Audio();
        a.canción();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClaudiList = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre_Lista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nombre_Programa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_anime = new javax.swing.JRadioButton();
        b_serie = new javax.swing.JRadioButton();
        b_documental = new javax.swing.JRadioButton();
        b_película = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        JS_Puntuación = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        Año = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        b_comedia = new javax.swing.JRadioButton();
        b_romance = new javax.swing.JRadioButton();
        b_terror = new javax.swing.JRadioButton();
        b_syfy = new javax.swing.JRadioButton();
        b_suspenso = new javax.swing.JRadioButton();
        b_acción = new javax.swing.JRadioButton();
        Guardar_Lista = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Crear_Programa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Nombre_Programa1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b_anime1 = new javax.swing.JRadioButton();
        b_serie1 = new javax.swing.JRadioButton();
        b_documental1 = new javax.swing.JRadioButton();
        b_película1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        JS_Puntuación1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        Año1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        b_comedia1 = new javax.swing.JRadioButton();
        b_romance1 = new javax.swing.JRadioButton();
        b_terror1 = new javax.swing.JRadioButton();
        b_syfy1 = new javax.swing.JRadioButton();
        b_suspenso1 = new javax.swing.JRadioButton();
        b_acción1 = new javax.swing.JRadioButton();
        Guardar_Lista1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Cb_Listap = new javax.swing.JComboBox<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Administrador = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenuItem();
        Reproducir = new javax.swing.JMenuItem();
        j_editar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        b_nombre = new javax.swing.JButton();
        b_Puntuación = new javax.swing.JButton();
        b_Estreno = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        b_Tipo = new javax.swing.JButton();
        b_Genero = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        Ingresar_Tipo = new javax.swing.JComboBox<>();
        jRadioButton4 = new javax.swing.JRadioButton();
        Ingresar_Genero = new javax.swing.JComboBox<>();
        jRadioButton5 = new javax.swing.JRadioButton();
        Ingresar_Nombre = new javax.swing.JTextField();
        Ingresar_Puntación = new javax.swing.JTextField();
        Ingresar_año = new javax.swing.JTextField();
        cargando = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Crear_ClaudiList = new javax.swing.JButton();
        Agregar_Programa = new javax.swing.JButton();
        Cargar_Archivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_Lista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de la Lista:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del programa:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Programa: ");

        buttonGroup1.add(b_anime);
        b_anime.setText("Anime");

        buttonGroup1.add(b_serie);
        b_serie.setText("Serie");

        buttonGroup1.add(b_documental);
        b_documental.setText("Documental");

        buttonGroup1.add(b_película);
        b_película.setText("Película");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Puntuación: ");

        JS_Puntuación.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Año de lanzamiento");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Genero");

        buttonGroup2.add(b_comedia);
        b_comedia.setText("Comedia ");

        buttonGroup2.add(b_romance);
        b_romance.setText("Romance");

        buttonGroup2.add(b_terror);
        b_terror.setText("terror");

        buttonGroup2.add(b_syfy);
        b_syfy.setText("Syfy");

        buttonGroup2.add(b_suspenso);
        b_suspenso.setText("Suspenso");

        buttonGroup2.add(b_acción);
        b_acción.setText("Acción");

        Guardar_Lista.setText("Guardar");
        Guardar_Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_ListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(JS_Puntuación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_anime)
                                .addGap(18, 18, 18)
                                .addComponent(b_serie)
                                .addGap(18, 18, 18)
                                .addComponent(b_documental)
                                .addGap(18, 18, 18)
                                .addComponent(b_película))
                            .addComponent(Nombre_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(b_comedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_romance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_terror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_syfy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_suspenso)
                        .addGap(18, 18, 18)
                        .addComponent(b_acción)))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(Nombre_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(Guardar_Lista)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(b_anime)
                    .addComponent(b_serie)
                    .addComponent(b_documental)
                    .addComponent(b_película))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JS_Puntuación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(b_comedia)
                    .addComponent(b_romance)
                    .addComponent(b_terror)
                    .addComponent(b_syfy)
                    .addComponent(b_suspenso)
                    .addComponent(b_acción))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(Guardar_Lista))
        );

        javax.swing.GroupLayout ClaudiListLayout = new javax.swing.GroupLayout(ClaudiList.getContentPane());
        ClaudiList.getContentPane().setLayout(ClaudiListLayout);
        ClaudiListLayout.setHorizontalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClaudiListLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        ClaudiListLayout.setVerticalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClaudiListLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Nombre del programa:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Tipo de Programa: ");

        buttonGroup1.add(b_anime1);
        b_anime1.setText("Anime");

        buttonGroup1.add(b_serie1);
        b_serie1.setText("Serie");

        buttonGroup1.add(b_documental1);
        b_documental1.setText("Documental");

        buttonGroup1.add(b_película1);
        b_película1.setText("Película");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Puntuación: ");

        JS_Puntuación1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Año de lanzamiento");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Genero");

        buttonGroup2.add(b_comedia1);
        b_comedia1.setText("Comedia ");

        buttonGroup2.add(b_romance1);
        b_romance1.setText("Romance");

        buttonGroup2.add(b_terror1);
        b_terror1.setText("terror");

        buttonGroup2.add(b_syfy1);
        b_syfy1.setText("Syfy");

        buttonGroup2.add(b_suspenso1);
        b_suspenso1.setText("Suspenso");

        buttonGroup2.add(b_acción1);
        b_acción1.setText("Acción");

        Guardar_Lista1.setText("Guardar");
        Guardar_Lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_Lista1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Añadir a Lista: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(Guardar_Lista1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(JS_Puntuación1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(b_comedia1)
                        .addGap(18, 18, 18)
                        .addComponent(b_romance1)
                        .addGap(18, 18, 18)
                        .addComponent(b_terror1)
                        .addGap(18, 18, 18)
                        .addComponent(b_syfy1)
                        .addGap(18, 18, 18)
                        .addComponent(b_suspenso1)
                        .addGap(18, 18, 18)
                        .addComponent(b_acción1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Año1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b_anime1)
                                .addGap(18, 18, 18)
                                .addComponent(b_serie1)
                                .addGap(18, 18, 18)
                                .addComponent(b_documental1)
                                .addGap(18, 18, 18)
                                .addComponent(b_película1))
                            .addComponent(Nombre_Programa1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cb_Listap, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nombre_Programa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(b_anime1)
                    .addComponent(b_serie1)
                    .addComponent(b_documental1)
                    .addComponent(b_película1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JS_Puntuación1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Año1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Cb_Listap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(b_comedia1)
                    .addComponent(b_romance1)
                    .addComponent(b_terror1)
                    .addComponent(b_syfy1)
                    .addComponent(b_suspenso1)
                    .addComponent(b_acción1))
                .addGap(26, 26, 26)
                .addComponent(Guardar_Lista1))
        );

        javax.swing.GroupLayout Crear_ProgramaLayout = new javax.swing.GroupLayout(Crear_Programa.getContentPane());
        Crear_Programa.getContentPane().setLayout(Crear_ProgramaLayout);
        Crear_ProgramaLayout.setHorizontalGroup(
            Crear_ProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(Crear_ProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Crear_ProgramaLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        Crear_ProgramaLayout.setVerticalGroup(
            Crear_ProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(Crear_ProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Crear_ProgramaLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Administrador.add(Eliminar);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        Administrador.add(Editar);

        Reproducir.setText("Stream");
        Reproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReproducirActionPerformed(evt);
            }
        });
        Administrador.add(Reproducir);

        j_editar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_nombre.setText("Guardar N");
        b_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nombreActionPerformed(evt);
            }
        });
        jPanel2.add(b_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 40));

        b_Puntuación.setText("Guardar P");
        b_Puntuación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_PuntuaciónActionPerformed(evt);
            }
        });
        jPanel2.add(b_Puntuación, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 100, 40));

        b_Estreno.setText("Guardar E");
        b_Estreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EstrenoActionPerformed(evt);
            }
        });
        jPanel2.add(b_Estreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, 40));

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup3.add(jRadioButton1);
        jRadioButton1.setText("Nombre");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 40));

        b_Tipo.setText("Guardar T");
        b_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TipoActionPerformed(evt);
            }
        });
        jPanel2.add(b_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 40));

        b_Genero.setText("Guardar G");
        b_Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_GeneroActionPerformed(evt);
            }
        });
        jPanel2.add(b_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 110, 40));

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setText("Puntuación");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 110, 40));

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setText("Estreno");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 90, 40));

        Ingresar_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anime ", "serie", "documental", "película" }));
        jPanel2.add(Ingresar_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 110, 50));

        jRadioButton4.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("Tipo");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, 40));

        Ingresar_Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "romance", "terror", "SyFy", "Suspenso", "accion" }));
        Ingresar_Genero.setToolTipText("");
        jPanel2.add(Ingresar_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 110, 50));

        jRadioButton5.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("Género");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 80, 50));
        jPanel2.add(Ingresar_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, 30));
        jPanel2.add(Ingresar_Puntación, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 40));
        jPanel2.add(Ingresar_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 130, 40));

        j_editar.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        jProgressBar2.setStringPainted(true);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Cargando archivo");

        jButton2.setText("Terminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout cargandoLayout = new javax.swing.GroupLayout(cargando.getContentPane());
        cargando.getContentPane().setLayout(cargandoLayout);
        cargandoLayout.setHorizontalGroup(
            cargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(cargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cargandoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        cargandoLayout.setVerticalGroup(
            cargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(cargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cargandoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));
        setResizable(false);

        Crear_ClaudiList.setText("Crear Claudilist");
        Crear_ClaudiList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_ClaudiListActionPerformed(evt);
            }
        });

        Agregar_Programa.setText("Agregar Programa");
        Agregar_Programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ProgramaActionPerformed(evt);
            }
        });

        Cargar_Archivo.setText("Cargar Archivo");
        Cargar_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar_ArchivoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Fecha", "Tipo", "Género"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        cb_Lista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ListaItemStateChanged(evt);
            }
        });

        jButton1.setText("Guardar  Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(255, 153, 0));
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(cb_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Crear_ClaudiList, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar_Programa)
                            .addComponent(Cargar_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(cb_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Crear_ClaudiList, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Agregar_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Cargar_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_ClaudiListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_ClaudiListActionPerformed
        ClaudiList.setModal(true);
        ClaudiList.pack();
        ClaudiList.setLocationRelativeTo(this);
        ClaudiList.setVisible(true);
    }//GEN-LAST:event_Crear_ClaudiListActionPerformed

    private void Agregar_ProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ProgramaActionPerformed
        if(cont==0){
            JOptionPane.showMessageDialog(this,"Debe primero tener una claudilist");
        }
        if(cont!=0){
        Crear_Programa.setModal(true);
        Crear_Programa.pack();
        Crear_Programa.setLocationRelativeTo(this);
        Crear_Programa.setVisible(true);
            
        }
    }//GEN-LAST:event_Agregar_ProgramaActionPerformed

    private void Guardar_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_ListaActionPerformed
        cont++;
        //Aquí creo mi lista y la guardo
        String nombre = "";
        int puntuación = 0;
        String fecha = "";
        String tipo = "";
        String genero = "";
        String Nombre_lista = "";
        Boolean f = true;

        try {
            nombre = Nombre_Programa.getText();

            puntuación = (int) JS_Puntuación.getValue();

            fecha = Año.getText();
            if (b_anime.isSelected()) {
                tipo = "Anime";
            }
            if (b_serie.isSelected()) {
                tipo = "Serie";
            }
            if (b_documental.isSelected()) {
                tipo = "Documental";
            }
            if (b_película.isSelected()) {
                tipo = "Película";
            }
            if (b_comedia.isSelected()) {
                genero = "Comedia";
            }
            if (b_romance.isSelected()) {
                genero = "Romance";
            }
            if (b_terror.isSelected()) {
                genero = "Terror";
            }
            if (b_syfy.isSelected()) {
                genero = "SyFy";
            }
            if (b_suspenso.isSelected()) {
                genero = "Suspenso";
            }
            if (b_acción.isSelected()) {
                genero = "Acción";
            }
            Nombre_lista = Nombre_Lista.getText();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al crear la Lista");
            f = false;
        }
        if (f == true) {
            JOptionPane.showMessageDialog(null, "Se ha guardado la lista exitosamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();
            Programas p = new Programas(nombre, puntuación, fecha, tipo, genero);
            cb_Lista.setModel(modelo);
            claudilist cl = new claudilist();
            cl.setNombre(Nombre_lista);
            cl.getLista().add(p);
            modelo.addElement(cl);
            Nombre_Programa.setText("");
            Nombre_Lista.setText("");
            Año.setText("");
            DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) Cb_Listap.getModel();
            Cb_Listap.setModel(modelo1);
            modelo1.addElement(cl);
            ClaudiList.setVisible(false);
        }

    }//GEN-LAST:event_Guardar_ListaActionPerformed

    private void cb_ListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ListaItemStateChanged
      //----------------------------------------------//
      //           Esto Actualiza la tabla y combo boxes
      //----------------------------------------------//
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        eliminar();
        if (evt.getStateChange() == 1) {

            claudilist c = (claudilist) modelo.getSelectedItem();

            for (Programas p : c.getLista()) {

                Object[] newRow = {
                    p.getNombre(),
                    p.getPuntuación(),
                    p.getFecha(),
                    p.getTipo(),
                    p.getGenero()
                };

                modelo2.addRow(newRow);
            }

        }
    }//GEN-LAST:event_cb_ListaItemStateChanged
    public void eliminar() {
        //---------------------------------------------------//
        //      Esto hace que no se repitan cosas en la tabla
        //---------------------------------------------------//
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //--------------------------------------------------//
        //Guardo la lista en archivos
        //--------------------------------------------------//
        if (cb_Lista.getSelectedIndex() >= 0) {

            try {
                ((claudilist) (cb_Lista.getSelectedItem())).escribirArchivo();
            } catch (IOException ex) {

            }
            
            JOptionPane.showMessageDialog(this, "El archivo se ha guardo correctamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Guardar_Lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_Lista1ActionPerformed
        String nombre = "";
        int puntuación = 0;
        String fecha = "";
        String tipo = "";
        String genero = "";

        Boolean f = true;

        try {
            nombre = Nombre_Programa1.getText();

            puntuación = (int) JS_Puntuación1.getValue();

            fecha = Año1.getText();
            if (b_anime1.isSelected()) {
                tipo = "Anime";
            }
            if (b_serie1.isSelected()) {
                tipo = "Serie";
            }
            if (b_documental1.isSelected()) {
                tipo = "Documental";
            }
            if (b_película1.isSelected()) {
                tipo = "Película";
            }
            if (b_comedia1.isSelected()) {
                genero = "Comedia";
            }
            if (b_romance1.isSelected()) {
                genero = "Romance";
            }
            if (b_terror1.isSelected()) {
                genero = "Terror";
            }
            if (b_syfy1.isSelected()) {
                genero = "SyFy";
            }
            if (b_suspenso1.isSelected()) {
                genero = "Suspenso";
            }
            if (b_acción1.isSelected()) {
                genero = "Acción";
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al crear Programa");
            f = false;
        }
        if (f == true) {
            JOptionPane.showMessageDialog(null, "Se ha guardado la lista exitosamente");
            DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();

            Programas p = new Programas(nombre, puntuación, fecha, tipo, genero);

            claudilist cl = (claudilist) Cb_Listap.getSelectedItem();

            cl.getLista().add(p);

            eliminar();
            for (Programas p1 : cl.getLista()) {

                Object[] newRow = {
                    p1.getNombre(),
                    p1.getPuntuación(),
                    p1.getFecha(),
                    p1.getTipo(),
                    p1.getGenero()
                };

                modelo2.addRow(newRow);
            }

            Nombre_Programa1.setText("");
            Nombre_Lista.setText("");
            Año.setText("");

            Crear_Programa.setVisible(false);
        }

    }//GEN-LAST:event_Guardar_Lista1ActionPerformed

    private void Cargar_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar_ArchivoActionPerformed
        //-----------------------------------------------------------//
        // cargo archivos ya creados
        //-----------------------------------------------------------//
        
        eliminar();
        jTable1.setVisible(false);
        DefaultTableModel models = (DefaultTableModel) jTable1.getModel();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Lista.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) Cb_Listap.getModel();

        try {
            ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
        } catch (Exception e) {
        }

        JFileChooser fileChooser = new JFileChooser("./");

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            cont++;
            try {

                Scanner sc = null;
                File archivo = fileChooser.getSelectedFile();
                claudilist c = new claudilist();

                String nombre = archivo.getName();
                int l = nombre.length();

                nombre = nombre.substring(0, l - 4);

                c.setNombre(nombre);
                modelo.setSelectedItem(c);

                sc = new Scanner(archivo);

                String file = "";

                while (sc.hasNext()) {
                    file += sc.next();

                }
                String resultado = file;

                sc = new Scanner(resultado);
                sc.useDelimiter("/");

                while (sc.hasNext()) {

                    Programas p = new Programas(sc.next(),
                            sc.nextInt(), sc.next(),
                            sc.next(), sc.next()
                    );

                    Object[] newRow = {
                        p.getNombre(),
                        p.getPuntuación(),
                        p.getFecha(),
                        p.getTipo(),
                        p.getGenero()
                    };
                    models.addRow(newRow);

                    c.getLista().add(p);
                    Cb_Listap.setModel(modelo2);

                }

                modelo2.addElement(c);
                modelo.addElement(c);
                jTable1.setModel(models);
                cb_Lista.setModel(modelo);

                cargando.pack();
                cargando.setVisible(true);
                Hilos_de_cargas x = new Hilos_de_cargas();
                jButton2.setVisible(false);
                
                // HILO DE JPROGRESS BAR
                x.start();
                x.setBarra(jProgressBar2);
                x.setAvanzar(true);
                x.setVive(true);
                x.setBotoncito(jButton2);
                jButton2.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        cargando.setVisible(false);
                        jTable1.setVisible(true);
                    }

                });
                cargando.setVisible(true);

            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_Cargar_ArchivoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.isMetaDown()) {
            if (jTable1.getSelectedRow() >= 0) {
                Administrador.show(jTable1, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       
        // -------------------------------------------------//
        //Eliminar objetos
        //-------------------------------------------------//
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        int index = jTable1.getSelectedRow();

        Programas p = new Programas(
                (String) modelo.getValueAt(index, 0),
                (int) modelo.getValueAt(index, 1),
                (String) modelo.getValueAt(index, 2),
                (String) modelo.getValueAt(index, 3),
                (String) modelo.getValueAt(index, 4)
        );
        ((claudilist) cb_Lista.getSelectedItem()).getLista().remove(index);
        modelo.removeRow(index);

        jTable1.setModel(modelo);

        JOptionPane.showMessageDialog(this, "Se ha removido la cancion de la playlist");
        try {
            ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        j_editar.setModal(true);
        j_editar.pack();
        j_editar.setLocationRelativeTo(this);
        j_editar.setVisible(true);
        
        Ingresar_Nombre.setVisible(false);
        Ingresar_Puntación.setVisible(false);
        Ingresar_año.setVisible(false);
        Ingresar_Tipo.setVisible(false);
        Ingresar_Genero.setVisible(false);

    }//GEN-LAST:event_EditarActionPerformed

    
                                               

                                            

                                        

  
    
    
    private void ReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReproducirActionPerformed
       
        Hilo h = new Hilo();
        h.setBarra(jProgressBar1);
        try{
        if(jProgressBar1.getValue()==0){
            h.start();
        }
            
        }catch(Exception e){
            
        }
        
        h.setAvanzar(true);
        h.setVive(true);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        int index = jTable1.getSelectedRow();
        String multi = (String) modelo.getValueAt(index, 0);

        h.setMultimedia(multi);

    }//GEN-LAST:event_ReproducirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_PuntuaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_PuntuaciónActionPerformed
 DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();

 if (jTable1.getSelectedRow() >= 0) {
     int indice = jTable1.getSelectedRow();
     if(Integer.parseInt(Ingresar_Puntación.getText())<10){
     ((claudilist) cb_Lista.getSelectedItem()).getLista().get(indice).setPuntuación(Integer.parseInt(Ingresar_Puntación.getText()));
        modelo1.setValueAt(Ingresar_Puntación.getText(), indice, 1);
     jTable1.setModel(modelo1);
         
     } 
     if(Integer.parseInt(Ingresar_Puntación.getText())>10){
         JOptionPane.showMessageDialog(null,"Tiene que ser un número del 1 al 10");
     }

     try {
         ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
     } catch (IOException ex) {

     }
 }
 Ingresar_Puntación.setText("");
 j_editar.setVisible(false);    }//GEN-LAST:event_b_PuntuaciónActionPerformed

    private void b_GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_GeneroActionPerformed
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
 DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Lista.getModel();
 if (jTable1.getSelectedRow() >= 0) {
     int indice = jTable1.getSelectedRow();
     jTable1.setModel(modelo1);
     String tipo = "";
     if(Ingresar_Genero.getSelectedIndex()==0){
       tipo = "Comedia";  
     }
     if(Ingresar_Genero.getSelectedIndex()==1){
       tipo = "Romance";  
     }
     if(Ingresar_Genero.getSelectedIndex()==2){
       tipo = "Terror";  
     }
     if(Ingresar_Genero.getSelectedIndex()==3){
       tipo = "Syfy";  
     }
     if(Ingresar_Genero.getSelectedIndex()==4){
       tipo = "Suspenso";  
     }
     if(Ingresar_Genero.getSelectedIndex()==5){
       tipo = "Acción";  
     }
     ((claudilist) cb_Lista.getSelectedItem()).getLista().get(indice).setTipo(tipo);
       modelo1.setValueAt(tipo, indice, 4);

     try {
         ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
     } catch (IOException ex) {

     }
 }
 
 j_editar.setVisible(false); 
    }//GEN-LAST:event_b_GeneroActionPerformed

    private void b_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TipoActionPerformed
         DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
 DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Lista.getModel();
 if (jTable1.getSelectedRow() >= 0) {
     int indice = jTable1.getSelectedRow();
     jTable1.setModel(modelo1);
     String tipo = "";
     if(Ingresar_Tipo.getSelectedIndex()==0){
       tipo = "Anime";  
     }
     if(Ingresar_Tipo.getSelectedIndex()==1){
       tipo = "Serie";  
     }
     if(Ingresar_Tipo.getSelectedIndex()==2){
       tipo = "Documental";  
     }
     if(Ingresar_Tipo.getSelectedIndex()==3){
       tipo = "Película";  
     }
     ((claudilist) cb_Lista.getSelectedItem()).getLista().get(indice).setTipo(tipo);
       modelo1.setValueAt(tipo, indice, 3);

     try {
         ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
     } catch (IOException ex) {

     }
 }
 
 j_editar.setVisible(false); 
    }//GEN-LAST:event_b_TipoActionPerformed

    private void b_EstrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EstrenoActionPerformed
 DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
 DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Lista.getModel();
 if (jTable1.getSelectedRow() >= 0) {
     int indice = jTable1.getSelectedRow();
     jTable1.setModel(modelo1);
     
     ((claudilist) cb_Lista.getSelectedItem()).getLista().get(indice).setFecha(Ingresar_año.getText());
       modelo1.setValueAt(Ingresar_año.getText(), indice, 2);

     try {
         ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
     } catch (IOException ex) {

     }
 }
 
 j_editar.setVisible(false);     }//GEN-LAST:event_b_EstrenoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Ingresar_Nombre.setVisible(true);
        Ingresar_Puntación.setVisible(false);
        Ingresar_año.setVisible(false);
        Ingresar_Tipo.setVisible(false);
        Ingresar_Genero.setVisible(false);
        //-------------------------------------//
        b_Puntuación.setVisible(false);
        b_Estreno.setVisible(false);
        b_Tipo.setVisible(false);
        b_Genero.setVisible(false);
        b_nombre.setVisible(true); 
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Ingresar_Nombre.setVisible(false);
        Ingresar_Puntación.setVisible(true);
        Ingresar_año.setVisible(false);
        Ingresar_Tipo.setVisible(false);
        Ingresar_Genero.setVisible(false);
        //-------------------------------------//
        b_nombre.setVisible(false);
        b_Puntuación.setVisible(true);
        b_Estreno.setVisible(false);
        b_Tipo.setVisible(false);
        b_Genero.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
       Ingresar_Nombre.setVisible(false);
        Ingresar_Puntación.setVisible(false);
        Ingresar_año.setVisible(true);
        Ingresar_Tipo.setVisible(false);
        Ingresar_Genero.setVisible(false);
        //-------------------------------------//
        b_nombre.setVisible(false);
        b_Puntuación.setVisible(false);
        b_Estreno.setVisible(true);
        b_Tipo.setVisible(false);
        b_Genero.setVisible(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        Ingresar_Nombre.setVisible(false);
        Ingresar_Puntación.setVisible(false);
        Ingresar_año.setVisible(false);
        Ingresar_Tipo.setVisible(true);
        Ingresar_Genero.setVisible(false);
        //-------------------------------------//
        b_nombre.setVisible(false);
        b_Puntuación.setVisible(false);
        b_Estreno.setVisible(false);
        b_Tipo.setVisible(true);
        b_Genero.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
          Ingresar_Nombre.setVisible(false);
        Ingresar_Puntación.setVisible(false);
        Ingresar_año.setVisible(false);
        Ingresar_Tipo.setVisible(false);
        Ingresar_Genero.setVisible(true);
        //-------------------------------------//
        b_nombre.setVisible(false);
        b_Puntuación.setVisible(false);
        b_Estreno.setVisible(false);
        b_Tipo.setVisible(false);
        b_Genero.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void b_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nombreActionPerformed
         DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
 DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Lista.getModel();
 if (jTable1.getSelectedRow() >= 0) {
     int indice = jTable1.getSelectedRow();
     
     jTable1.setModel(modelo1);
            modelo1.setValueAt(Ingresar_Nombre.getText(), indice, 0);

     ((claudilist) cb_Lista.getSelectedItem()).getLista().get(indice).setNombre(Ingresar_Nombre.getText());

     try {
         ((claudilist) cb_Lista.getSelectedItem()).escribirArchivo();
     } catch (IOException ex) {

     }
 }
 Ingresar_Nombre.setText("");
 j_editar.setVisible(false);
    }//GEN-LAST:event_b_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lab8_WalterReyes x = new Lab8_WalterReyes();

                x.pack();
                
                x.setVisible(true);
                Audio a = new Audio();
                a.start();
                a.setAvanzar(true);
                a.setVive(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Administrador;
    private javax.swing.JButton Agregar_Programa;
    private javax.swing.JTextField Año;
    private javax.swing.JTextField Año1;
    private javax.swing.JButton Cargar_Archivo;
    private javax.swing.JComboBox<String> Cb_Listap;
    private javax.swing.JDialog ClaudiList;
    private javax.swing.JButton Crear_ClaudiList;
    private javax.swing.JDialog Crear_Programa;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JButton Guardar_Lista;
    private javax.swing.JButton Guardar_Lista1;
    private javax.swing.JComboBox<String> Ingresar_Genero;
    private javax.swing.JTextField Ingresar_Nombre;
    private javax.swing.JTextField Ingresar_Puntación;
    private javax.swing.JComboBox<String> Ingresar_Tipo;
    private javax.swing.JTextField Ingresar_año;
    private javax.swing.JSpinner JS_Puntuación;
    private javax.swing.JSpinner JS_Puntuación1;
    private javax.swing.JTextField Nombre_Lista;
    private javax.swing.JTextField Nombre_Programa;
    private javax.swing.JTextField Nombre_Programa1;
    private javax.swing.JMenuItem Reproducir;
    private javax.swing.JButton b_Estreno;
    private javax.swing.JButton b_Genero;
    private javax.swing.JButton b_Puntuación;
    private javax.swing.JButton b_Tipo;
    private javax.swing.JRadioButton b_acción;
    private javax.swing.JRadioButton b_acción1;
    private javax.swing.JRadioButton b_anime;
    private javax.swing.JRadioButton b_anime1;
    private javax.swing.JRadioButton b_comedia;
    private javax.swing.JRadioButton b_comedia1;
    private javax.swing.JRadioButton b_documental;
    private javax.swing.JRadioButton b_documental1;
    private javax.swing.JButton b_nombre;
    private javax.swing.JRadioButton b_película;
    private javax.swing.JRadioButton b_película1;
    private javax.swing.JRadioButton b_romance;
    private javax.swing.JRadioButton b_romance1;
    private javax.swing.JRadioButton b_serie;
    private javax.swing.JRadioButton b_serie1;
    private javax.swing.JRadioButton b_suspenso;
    private javax.swing.JRadioButton b_suspenso1;
    private javax.swing.JRadioButton b_syfy;
    private javax.swing.JRadioButton b_syfy1;
    private javax.swing.JRadioButton b_terror;
    private javax.swing.JRadioButton b_terror1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JDialog cargando;
    private javax.swing.JComboBox<String> cb_Lista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog j_editar;
    // End of variables declaration//GEN-END:variables
int cont = 0;
}
